export const HOME = '/home'
export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const RESETPWD = '/resetpassword'
export const PRODUCTIONS = '/productions'
export const CALLSHEETS = '/callsheets'